name: Use only
apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

on:
  workflow_dispatch:

jobs:
  usetheimage:
    steps:
      - uses: docker://476449643511.dkr.ecr.eu-north-1.amazonaws.com/mlcb/privaterepository002:latest
        run: cat /test2.txt
